### ISSUE TITLE
Example project doesn't work

### ISSUE THREAD

**Issue by jozan** [pressly/react-native-radio-button-classic#1]
When trying to run Example project, packager gives the following error:

```
[13:51:52] <START> fs crawl
[13:51:53] <END>   fs crawl (394ms)
Unable to resolve module Dimensions from [..omitted..]/react-native-radio-button-classic/Example/node_modules/react-native-radio-button-classic/lib/index.js
Unable to resolve module Dimensions from [..omitted..]/react-native-radio-button-classic/Example/node_modules/react-native-radio-button-classic/lib/index.js
[13:52:26] <START> request:/index.ios.bundle
[13:52:26] <START> find dependencies
[13:52:26] <END>   find dependencies (71ms)
[13:52:26] <START> transform
[13:52:26] <END>   transform (46ms)
[13:52:26] <END>   request:/index.ios.bundle (127ms)
```

Redbox error in simulator:

```
Syntax error: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
{
  "line":  1450,
  "source": "http://localhost:8081/index.ios.bundle"
}
```

**Comment by alinz** [comment]
@jozan, Thanks for trying it out. I'd like to know couple of things,
1: Are you using iojs or node?
2: Have you update your watchman?

I can give you a fix very quickly if you provide me this info.

Thanks,

**Comment by jozan** [comment]
Watchman version is `3.7.0` and I'm using iosj `3.0.0`.

**Comment by alinz** [comment]
I think I have forked my iojs and react-native to make these kind of errors go away.
However, You can do one of the following options in order to fix this issue:

1: in `index.ios.js` remove [this line](https://github.com/pressly/react-native-radio-button-classic/blob/master/Example/index.ios.js#L5).
2: replace `const` on this [line](https://github.com/pressly/react-native-radio-button-classic/blob/master/Example/index.ios.js#L19) and [that](https://github.com/pressly/react-native-radio-button-classic/blob/master/Example/index.ios.js#L35) to `var`

I will fix this in few min and push it to both npm and github.

Cheers, :beer:

**Comment by alinz** [comment]
I have pushed the fix. I will close this issue.

**Comment by jozan** [comment]
I still get `Unable to resolve module Dimensions` error but it works nonetheless! Thanks :+1:

**Comment by alinz** [comment]
That is related to internal `react-native`, The react-native team is focusing on putting all internal components under `react-native` umbrella. So in the future, if you want to get access to `Dimensions` or any utility, you have to get it from `react-native` directly.

For example,

instead of 

``` js
var Dimensions = require('Dimensions');
```

we need to do this

``` js
var React = require('react-native');
var { Dimensions } = React;
```

**Comment by jozan** [comment]
Okay, can I already use `var { Dimensions } = React;`?

**Comment by alinz** [comment]
As long as you are using react-native 0.8 and above you should be fine. I think just to be sure you can take a look at the [release notes](https://github.com/facebook/react-native/tags). The reason I use the old one because I wanted to be compatible for any version of `react-native`.

**Comment by jozan** [comment]
This is totally derailed from the issue at hand but one quick question. If you want to be backwards compatible with previous versions do you mind PR's that use `Animated`?

**Comment by alinz** [comment]
well as long as PR contains minimum required react-native at this [line](https://github.com/pressly/react-native-radio-button-classic/blob/master/package.json#L15) it should be fine. I'm using `peerDependencies` to target the specific `react-native`.

**Comment by jozan** [comment]
Thanks a lot!

:baby_chick:
